name: TELEBOT-CICD
on:
  push:
    branches:
        - develop

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make linux push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with: 
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          author_email: actionsBot
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "update version $VERSION in helm"